import { ReportWidget } from '../stores/useWorkbenchStore'

const HTML_TEMPLATE = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Analysis Report</title>
  <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f4f4f5; margin: 0; padding: 20px; }
    .header { margin-bottom: 24px; text-align: center; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(500px, 1fr)); gap: 24px; max-width: 1400px; margin: 0 auto; }
    .card { background: white; border-radius: 12px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); display: flex; flex-direction: column; }
    .card-title { font-size: 1.125rem; font-weight: 600; color: #18181b; margin-bottom: 8px; }
    .card-subtitle { font-size: 0.875rem; color: #71717a; margin-bottom: 16px; }
    .chart-container { width: 100%; height: 350px; flex: 1; }
    .big-number { font-size: 3rem; font-weight: 700; color: #18181b; text-align: center; margin: auto; }
    .summary { font-size: 0.875rem; color: #71717a; margin-top: 16px; border-top: 1px solid #f4f4f5; padding-top: 12px; }
    .insights { margin-top: 8px; background-color: #fff7ed; border-left: 4px solid #fdba74; padding: 12px; border-radius: 0 4px 4px 0; }
    .insights h4 { font-size: 0.875rem; font-weight: 600; color: #9a3412; margin: 0 0 8px 0; }
    .insights ul { margin: 0; padding: 0; list-style: none; font-size: 0.875rem; color: #c2410c; }
    .insights li { display: flex; align-items: start; gap: 8px; margin-bottom: 4px; }
    .insights li::before { content: "•"; color: #f97316; }

    /* Table Styles */
    .table-container { overflow-x: auto; width: 100%; margin-top: 16px; }
    table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
    th { text-align: left; padding: 8px 12px; background-color: #fafafa; border-bottom: 1px solid #e4e4e7; font-weight: 600; color: #52525b; }
    td { padding: 8px 12px; border-bottom: 1px solid #f4f4f5; color: #18181b; }
    tr:hover { background-color: #fafafa; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Analysis Report</h1>
    <p style="color: #71717a">Generated by Wansan Studio</p>
  </div>
  <div class="grid" id="app"></div>

  <script>
    const reports = __DATA_PLACEHOLDER__;

    const container = document.getElementById('app');

    reports.forEach((report, index) => {
      const card = document.createElement('div');
      card.className = 'card';
      
      // Determine Content Type
      let contentHtml = '';
      
      // Check for Big Number: Single row, single value (or keys <= 1 to be safe)
      const isBigNumber = report.chartType === 'table' && report.data && report.data.length === 1 && Object.keys(report.data[0]).length <= 1;
      
      // Check for Table: Explicit table type or missing chart config
      const isTable = !isBigNumber && (report.chartType === 'table' || !report.vizConfig || !report.vizConfig.x_axis || !report.vizConfig.y_axis);
      
      // Check for Chart
      const isChart = !isBigNumber && !isTable && report.vizConfig && report.vizConfig.x_axis && report.vizConfig.y_axis;

      if (isBigNumber) {
         const val = Object.values(report.data[0])[0];
         let displayVal = val;
         if (typeof val === 'number') {
            displayVal = val.toLocaleString();
         }
         contentHtml = \`<div class="big-number">\${displayVal}</div>\`;
      } else if (isChart) {
         contentHtml = \`<div id="chart-\${index}" class="chart-container"></div>\`;
      } else if (isTable) {
         contentHtml = \`<div id="table-\${index}" class="table-container"></div>\`;
      }

      // Render Card Structure
      let summaryHtml = '';
      if (report.summary) {
        summaryHtml += \`<div class="summary">\${report.summary}</div>\`;
      }
      if (report.insights && report.insights.length > 0) {
        summaryHtml += \`
          <div class="insights">
            <h4>💡 Key Insights</h4>
            <ul>
              \${report.insights.map(i => \`<li>\${i}</li>\`).join('')}
            </ul>
          </div>
        \`;
      }

      card.innerHTML = \`
        <div class="card-title">\${report.title}</div>
        \${report.subtitle ? \`<div class="card-subtitle">\${report.subtitle}</div>\` : ''}
        \${contentHtml}
        \${summaryHtml}
      \`;
      container.appendChild(card);

      // --- Logic: Render Table ---
      if (isTable && report.data && report.data.length > 0) {
        const tableContainer = document.getElementById(\`table-\${index}\`);
        if (tableContainer) {
            const columns = Object.keys(report.data[0]);
            const rows = report.data.slice(0, 100); // Limit to 100 rows for performance
            
            const table = document.createElement('table');
            const thead = document.createElement('thead');
            const tbody = document.createElement('tbody');
            
            // Header
            const headerRow = document.createElement('tr');
            columns.forEach(col => {
                const th = document.createElement('th');
                th.textContent = col;
                headerRow.appendChild(th);
            });
            thead.appendChild(headerRow);
            
            // Body
            rows.forEach(row => {
                const tr = document.createElement('tr');
                columns.forEach(col => {
                    const td = document.createElement('td');
                    td.textContent = row[col];
                    tr.appendChild(td);
                });
                tbody.appendChild(tr);
            });
            
            table.appendChild(thead);
            table.appendChild(tbody);
            tableContainer.appendChild(table);
        }
      }

      // --- Logic: Render Chart (Mirroring A4Chart.tsx) ---
      if (isChart) {
        const chartDom = document.getElementById(\`chart-\${index}\`);
        if (chartDom) {
            const myChart = echarts.init(chartDom);
            
            const { x_axis, y_axis, series_name } = report.vizConfig;
            const data = report.data || [];
            
            const xData = data.map(item => item[x_axis]);
            const yData = data.map(item => item[y_axis]);
            const type = report.chartType === 'area' ? 'line' : (report.chartType || 'bar');
            
            // Base Option Construction
            let option = {
                tooltip: {
                    trigger: 'axis',
                },
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true,
                },
                xAxis: {
                    type: 'category',
                    data: xData,
                    axisLabel: { interval: 0, rotate: 30 },
                },
                yAxis: {
                    type: 'value',
                },
                series: [
                    {
                        name: series_name || y_axis,
                        type: type,
                        data: yData,
                        itemStyle: {
                            color: '#4F46E5', // Indigo-600 matching React app
                        },
                        // Area Style handling
                        ...(report.chartType === 'area' ? { areaStyle: {} } : {})
                    },
                ],
            };
            
            // Pie Chart Override
            if (report.chartType === 'pie') {
                option = {
                    tooltip: { trigger: 'item' },
                    series: [
                        {
                            name: series_name || y_axis,
                            type: 'pie',
                            radius: '50%',
                            data: data.map(item => ({
                                value: item[y_axis],
                                name: item[x_axis],
                            })),
                            emphasis: {
                                itemStyle: {
                                    shadowBlur: 10,
                                    shadowOffsetX: 0,
                                    shadowColor: 'rgba(0, 0, 0, 0.5)',
                                },
                            },
                        },
                    ],
                };
            }

            try {
                myChart.setOption(option);
                // Handle Resize
                window.addEventListener('resize', () => {
                    myChart.resize();
                });
            } catch (e) {
                console.error('Chart init failed', e);
                chartDom.innerHTML = 'Chart Render Error';
            }
        }
      }
    });
  </script>
</body>
</html>
`

export async function exportDashboardToHtml(reports: ReportWidget[]) {
  // 1. Serialize Data
  const dataJson = JSON.stringify(reports.map(r => ({
    title: r.reportData.title,
    subtitle: r.reportData.subtitle,
    summary: r.reportData.summary,
    insights: r.reportData.insights,
    vizConfig: r.reportData.vizConfig,
    data: r.reportData.tableData,
    chartType: r.reportData.chartType
  })))

  // 2. Inject Data
  const finalHtml = HTML_TEMPLATE.replace('__DATA_PLACEHOLDER__', dataJson)

  // 3. Save File via Electron IPC
  try {
      const fileName = `Report_${new Date().toISOString().split('T')[0]}.html`
      await (window.electronAPI as any).saveFile(finalHtml, 'html', fileName)
  } catch (err) {
      console.error('Failed to save HTML report', err)
      throw err
  }
}
