import React from 'react'

interface A4CanvasProps {
  children: React.ReactNode
  title?: string
  className?: string
  showPrintStyles?: boolean
}

export function A4Canvas({ 
  children, 
  title = "数据报表", 
  className = "",
  showPrintStyles = false 
}: A4CanvasProps) {
  return (
    <div className={`flex justify-center ${className}`}>
      {/* A4 纸容器 - 210mm x 297mm 比例 (约 1:1.414) */}
      <div 
        className={`
          bg-white shadow-lg border border-gray-200 
          w-full max-w-4xl
          ${showPrintStyles ? 'print:shadow-none print:border-none' : ''}
        `}
        style={{
          aspectRatio: '210 / 297', // A4 纸比例
          minHeight: '800px' // 最小高度确保内容可见
        }}
      >
        {/* 页面内容 */}
        <div className="h-full flex flex-col p-8 print:p-6">
          {children}
        </div>
      </div>
    </div>
  )
}

// A4 画布的各个区域组件
interface A4HeaderProps {
  title: string
  subtitle?: string
  logo?: string
  timestamp?: Date
  className?: string
}

export function A4Header({ 
  title, 
  subtitle, 
  logo, 
  timestamp = new Date(), 
  className = "" 
}: A4HeaderProps) {
  return (
    <header className={`border-b border-gray-200 pb-4 mb-6 ${className}`}>
      <div className="flex items-start justify-between">
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-gray-900 mb-1">
            {title}
          </h1>
          {subtitle && (
            <p className="text-sm text-gray-600">
              {subtitle}
            </p>
          )}
        </div>
        
        <div className="flex items-center gap-4">
          {logo && (
            <img 
              src={logo} 
              alt="Logo" 
              className="h-12 w-auto object-contain"
            />
          )}
          <div className="text-right text-sm text-gray-500">
            <div>生成时间</div>
            <div className="font-mono">
              {timestamp.toLocaleString('zh-CN')}
            </div>
          </div>
        </div>
      </div>
    </header>
  )
}

interface A4SectionProps {
  title?: string
  children: React.ReactNode
  className?: string
}

export function A4Section({ title, children, className = "" }: A4SectionProps) {
  return (
    <section className={`mb-6 ${className}`}>
      {title && (
        <h2 className="text-lg font-semibold text-gray-800 mb-3 border-l-4 border-orange-500 pl-3">
          {title}
        </h2>
      )}
      <div>
        {children}
      </div>
    </section>
  )
}

export function A4Footer({ className = "" }: { className?: string }) {
  return (
    <footer className={`mt-auto pt-4 border-t border-gray-200 text-center ${className}`}>
      <div className="text-xs text-gray-400">
        Generated by <span className="font-semibold text-orange-600">Wansan Studio</span> - 数据聚宝，日进斗金
      </div>
    </footer>
  )
}

// 数据摘要组件
interface A4SummaryProps {
  content: string
  insights?: string[]
  className?: string
}

export function A4Summary({ content, insights, className = "" }: A4SummaryProps) {
  return (
    <div className={`prose prose-sm max-w-none ${className}`}>
      <div className="text-gray-700 leading-relaxed mb-4">
        {content}
      </div>

      {insights && insights.length > 0 && (
        <div className="bg-orange-50 border-l-4 border-orange-400 p-4 rounded-r">
          <h4 className="text-sm font-semibold text-orange-800 mb-2">💡 关键洞察</h4>
          <ul className="text-sm text-orange-700 space-y-1">
            {insights.map((insight, index) => (
              <li key={index} className="flex items-start gap-2">
                <span className="text-orange-500 mt-1">•</span>
                <span>{insight}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

// 图表占位组件
interface A4ChartPlaceholderProps {
  type?: 'bar' | 'line' | 'pie' | 'area'
  title?: string
  className?: string
}

export function A4ChartPlaceholder({
  type = 'bar',
  title = "数据图表",
  className = ""
}: A4ChartPlaceholderProps) {
  const chartIcons = {
    bar: '📊',
    line: '📈',
    pie: '🥧',
    area: '📉'
  }

  return (
    <div className={`
      h-64 border-2 border-dashed border-gray-300 rounded-lg
      flex flex-col items-center justify-center bg-gray-50 ${className}
    `}>
      <div className="text-4xl mb-2">{chartIcons[type]}</div>
      <div className="text-lg font-medium text-gray-600 mb-1">{title}</div>
      <div className="text-sm text-gray-500">图表将在此处显示</div>
    </div>
  )
}

// 数据表格组件
interface A4DataTableProps {
  data: Array<Record<string, any>>
  maxRows?: number
  className?: string
}

export function A4DataTable({ data, maxRows = 20, className = "" }: A4DataTableProps) {
  if (!data || data.length === 0) {
    return (
      <div className={`text-center py-8 text-gray-500 ${className}`}>
        暂无数据
      </div>
    )
  }

  const displayData = data.slice(0, maxRows)
  const columns = Object.keys(data[0])
  const hasMore = data.length > maxRows

  return (
    <div className={className}>
      <div className="overflow-x-auto">
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="bg-gray-50">
              {columns.map((column) => (
                <th
                  key={column}
                  className="px-3 py-2 text-left font-medium text-gray-700 border-b border-gray-200"
                >
                  {column}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {displayData.map((row, index) => (
              <tr key={index} className="hover:bg-gray-50">
                {columns.map((column) => (
                  <td
                    key={column}
                    className="px-3 py-2 text-gray-900 border-b border-gray-100"
                  >
                    {row[column]}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {hasMore && (
        <div className="mt-3 text-center text-sm text-gray-500">
          显示前 {maxRows} 条，共 {data.length} 条数据
        </div>
      )}
    </div>
  )
}

// 预设的 A4 报表布局
interface A4ReportLayoutProps {
  title: string
  subtitle?: string
  summary?: string
  insights?: string[]
  chartType?: 'bar' | 'line' | 'pie' | 'area'
  chartTitle?: string
  tableData?: Array<Record<string, any>>
  logo?: string
  className?: string
}

export function A4ReportLayout({
  title,
  subtitle,
  summary,
  insights,
  chartType = 'bar',
  chartTitle,
  tableData,
  logo,
  className = ""
}: A4ReportLayoutProps) {
  return (
    <A4Canvas className={className}>
      <A4Header
        title={title}
        subtitle={subtitle}
        logo={logo}
      />

      {summary && (
        <A4Section title="数据摘要">
          <A4Summary content={summary} insights={insights} />
        </A4Section>
      )}

      <A4Section title="数据可视化">
        <A4ChartPlaceholder type={chartType} title={chartTitle} />
      </A4Section>

      {tableData && tableData.length > 0 && (
        <A4Section title="数据明细">
          <A4DataTable data={tableData} />
        </A4Section>
      )}

      <A4Footer />
    </A4Canvas>
  )
}
