export const DISCLAIMER_TEXT_ZH = `
# 免责声明 / Legal Disclaimer

**生效日期 / Effective Date**: 2025-12-01

感谢您选择 Wansan Studio（以下简称“本软件”）。在使用本软件前，请务必仔细阅读以下条款。

## 1. AI 生成内容免责 (AI Generation)
本软件利用人工智能技术（LLM）将自然语言转换为 SQL 查询代码和可视化图表。
*   **不保证准确性**：AI 可能会产生“幻觉”或逻辑错误。生成的报表、数据计算结果仅供参考。
*   **人工核对义务**：用户在依据本软件生成的分析结果做出任何商业决策（如财务转账、库存采购、税务申报）前，**必须**对底层数据和 SQL 逻辑进行人工核对。
*   **责任豁免**：开发者不对因使用本软件生成的错误数据而导致的任何直接或间接损失（包括但不限于利润损失、商业中断）承担责任。

## 2. 数据隐私与安全 (Data Privacy)
本软件采用 **Local-First (本地优先)** 架构。
*   **数据不出域**：您的原始 Excel/CSV 文件仅存储在您设备的本地硬盘与内存中，**绝不会**上传至开发者的服务器。
*   **第三方传输**：仅有文件的元数据（Schema、列名）会被发送至您配置的 AI 服务商（如 OpenAI）。
*   **保管责任**：请妥善保管您的设备及 API Key。因用户设备被黑客攻击或 API Key 泄露导致的数据风险，由用户自行承担。

## 3. 第三方服务 (Third-Party Services)
本软件采用了“自带密钥 (BYOK)”模式。
*   用户需自行获取并配置 OpenAI / DeepSeek 等服务的 API Key。
*   用户需自行遵守相关服务商的使用条款（ToS）。本软件与 OpenAI 等公司无附属关系。

## 4. 软件许可 (License)
本软件为 **闭源商业软件 (Proprietary Software)**。
*   未经开发者书面许可，严禁对本软件进行反编译、逆向工程或破解。
*   严禁将本软件用于非法用途。

---

**使用本软件即代表您已阅读并同意上述条款。**
`

export const DISCLAIMER_TEXT_EN = `
# Legal Disclaimer

**Effective Date**: 2025-12-01

Thank you for choosing Wansan Studio ("the Software"). Please read the following terms carefully before using the Software.

## 1. AI Generation Disclaimer
This Software utilizes artificial intelligence (LLM) to convert natural language into SQL queries and visual charts.
*   **No Guarantee of Accuracy**: AI may produce "hallucinations" or logic errors. Generated reports and calculations are for reference only.
*   **Mandatory Human Verification**: Users **must** manually verify underlying data and SQL logic before making any business decisions (e.g., financial transfers, inventory purchases, tax filings) based on the analysis results generated by this Software.
*   **Liability Waiver**: The Developer shall not be liable for any direct or indirect losses (including but not limited to loss of profits, business interruption) resulting from the use of erroneous data generated by this Software.

## 2. Data Privacy & Security
This Software adopts a **Local-First** architecture.
*   **Data Sovereignty**: Your original Excel/CSV files are stored ONLY on your local hard drive and memory. They are **NEVER** uploaded to the Developer's servers.
*   **Third-Party Transmission**: Only file metadata (Schema, column names) is sent to your configured AI provider (e.g., OpenAI).
*   **Custody Responsibility**: Please safeguard your device and API Key. The user bears sole responsibility for data risks resulting from device hacking or API Key leakage.

## 3. Third-Party Services
This Software operates on a "Bring Your Own Key (BYOK)" model.
*   Users must obtain and configure API Keys for services like OpenAI / DeepSeek independently.
*   Users must comply with the Terms of Service (ToS) of relevant providers. This Software is not affiliated with OpenAI or other providers.

## 4. License
This Software is **Proprietary Software**.
*   Decompiling, reverse engineering, or cracking this Software is strictly prohibited without written permission from the Developer.
*   Using this Software for illegal purposes is strictly prohibited.

---

**By using this Software, you acknowledge that you have read and agreed to the above terms.**
`
