import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Minimal i18n for export
i18n
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        common: {
          'summary': 'Summary',
          'generated_time': 'Generated At',
          'no_chart_data': 'No Data',
          'page_of': 'Page {{page}} of {{total}}',
          'data_detail': 'Data Detail',
          'ai_insight': 'Business Insight',
          'untitled_chart': 'Untitled Chart',
          'analysis_report': 'Business Analysis Report',
          'default_report_title': 'Data Report',
          'no_pinned_reports': 'Add charts to your dashboard to build a report.',
          'untitled_section': 'Untitled Section',
          'insight_summary': 'Summary',
          'insight_findings': 'Key Findings',
          'insight_recommendation': 'Recommendation',
          'insight_anchors': 'Anchors',
          'generated_by_wansan': 'Generated by Wansan Studio',
          'untitled_report': 'Untitled Report'
        },
        chat: {
            'lineage_engine': 'Wansan Engine',
            'lineage_stats': '{{rowCount}} rows'
        }
      },
      zh: {
        common: {
          'summary': '摘要',
          'generated_time': '生成时间',
          'no_chart_data': '暂无数据',
          'page_of': '第 {{page}} 页 / 共 {{total}} 页',
          'data_detail': '数据详情',
          'ai_insight': '业务洞察',
          'untitled_chart': '未命名图表',
          'analysis_report': '分析报告',
          'default_report_title': '数据报表',
          'no_pinned_reports': '暂无图表。请在看板中添加图表以生成报告。',
          'untitled_section': '未命名章节',
          'insight_summary': '概览',
          'insight_findings': '关键发现',
          'insight_recommendation': '建议',
          'insight_anchors': '锚点',
          'generated_by_wansan': '由万三 (Wansan Studio) 生成',
          'untitled_report': '未命名报表'
        },
        chat: {
            'lineage_engine': '万三引擎',
            'lineage_stats': '{{rowCount}} 行'
        }
      }
    },
    lng: 'zh', // Default, will be overridden by snapshot if needed
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  })

export default i18n
