import React from 'react'
import { useTranslation } from 'react-i18next'

export function DashboardHeader() {
  const { t } = useTranslation('common')
  const snapshot = (window as any).__WANSAN_SNAPSHOT__
  const title = snapshot?.meta?.title || t('untitled_report')

  return (
    <div className="h-14 px-6 flex items-center justify-between bg-white border-b border-zinc-200">
      <div className="font-bold text-lg text-zinc-800 flex items-center gap-2">
        <span className="w-2 h-6 bg-black rounded-sm"></span>
        {title}
      </div>
      <div className="text-xs text-zinc-400 font-mono">
        {'Generated by Wansan Studio'}
      </div>
    </div>
  )
}
