import { DatabaseService } from '../database/duckdb'

/**
 * Validates SQL to prevent potentially destructive operations.
 * @param sql The SQL string to validate.
 * @returns True if the SQL is safe to execute, otherwise throws an error.
 */
function validateSQL(sql: string): boolean {
  // A simple check for read-only commands.
  const upperSql = sql.trim().toUpperCase()
  if (!upperSql.startsWith('SELECT') && !upperSql.startsWith('WITH')) {
    throw new Error('Only SELECT and WITH statements are allowed.')
  }

  const forbiddenKeywords = [
    'DROP',
    'DELETE',
    'INSERT',
    'UPDATE',
    'CREATE',
    'ALTER',
  ]
  for (const keyword of forbiddenKeywords) {
    if (upperSql.includes(` ${keyword} `)) {
      throw new Error(
        `Execution of forbidden SQL keyword "${keyword}" is disabled.`
      )
    }
  }
  return true
}

/**
 * Executes a SQL query generated by the AI and returns the result.
 *
 * @param sql The SQL query string to execute.
 * @param databaseService The DatabaseService instance.
 * @returns A promise that resolves to the query result data.
 */
export async function executeSQL(
  sql: string,
  databaseService: DatabaseService
): Promise<{ data: any[]; columnTypes: Record<string, string> }> {
  validateSQL(sql)

  try {
    const result = await databaseService.queryWithSchema(sql)
    return result
  } catch (error) {
    console.error('SQL Execution Error:', error)
    throw error
  }
}
