import { NativeDatabaseService } from '../services/native-db-service'

/**
 * Validates SQL to prevent potentially destructive operations.
 * @param sql The SQL string to validate.
 * @returns True if the SQL is safe to execute, otherwise throws an error.
 */
function validateSQL(sql: string): boolean {
  // A simple check for read-only commands.
  const upperSql = sql.trim().toUpperCase()

  // [Smart Metrics] Allow View Creation
  if (upperSql.startsWith('CREATE OR REPLACE VIEW')) {
    return true
  }

  // [Introspection] Allow DESCRIBE
  if (upperSql.startsWith('DESCRIBE') || upperSql.startsWith('DESC')) {
    return true
  }

  if (!upperSql.startsWith('SELECT') && !upperSql.startsWith('WITH')) {
    throw new Error('Only SELECT and WITH statements are allowed.')
  }

  const forbiddenKeywords = [
    'DROP',
    'DELETE',
    'INSERT',
    'UPDATE',
    // 'CREATE', // Allowed for Views (checked above for start)
    'ALTER',
  ]
  for (const keyword of forbiddenKeywords) {
    if (upperSql.includes(` ${keyword} `)) {
      throw new Error(
        `Execution of forbidden SQL keyword "${keyword}" is disabled.`
      )
    }
  }
  // Explicitly check for CREATE in the middle if it's not a view creation
  if (
    upperSql.includes(' CREATE ') &&
    !upperSql.startsWith('CREATE OR REPLACE VIEW')
  ) {
    throw new Error('Execution of forbidden SQL keyword "CREATE" is disabled.')
  }

  return true
}

/**
 * Executes a SQL query generated by the AI and returns the result.
 *
 * @param sql The SQL query string to execute.
 * @param databaseService The DatabaseService instance.
 * @returns A promise that resolves to the query result data.
 */
export async function executeSQL(
  sql: string,
  databaseService: NativeDatabaseService
): Promise<{ data: any[]; columnFields: Array<{ name: string; type: string }> }> {
  validateSQL(sql)

  try {
    const result = await databaseService.queryWithSchema(sql)
    return result
  } catch (error) {
    console.error('SQL Execution Error:', error)
    throw error
  }
}
