import duckdb from 'duckdb'

/**
 * Validates SQL to prevent potentially destructive operations.
 * @param sql The SQL string to validate.
 * @returns True if the SQL is safe to execute, otherwise throws an error.
 */
function validateSQL(sql: string): boolean {
  // A simple check for read-only commands.
  const upperSql = sql.trim().toUpperCase()
  if (!upperSql.startsWith('SELECT') && !upperSql.startsWith('WITH')) {
    throw new Error('Only SELECT and WITH statements are allowed.')
  }

  const forbiddenKeywords = [
    'DROP',
    'DELETE',
    'INSERT',
    'UPDATE',
    'CREATE',
    'ALTER',
  ]
  for (const keyword of forbiddenKeywords) {
    if (upperSql.includes(` ${keyword} `)) {
      throw new Error(
        `Execution of forbidden SQL keyword "${keyword}" is disabled.`
      )
    }
  }
  return true
}

/**
 * Post-processes DuckDB results to handle types not directly supported by JSON, like BigInt.
 * @param data The raw data array from DuckDB.
 * @returns A new array with values safe for JSON serialization.
 */
function postProcessResult(data: any[]): any[] {
  // DuckDB may return BigInt, which is not supported by JSON.stringify by default.
  // A simple and safe way is to stringify and parse back, with a replacer for BigInt.
  return JSON.parse(
    JSON.stringify(data, (_key, value) =>
      typeof value === 'bigint' ? value.toString() : value
    )
  )
}

/**
 * Executes a SQL query generated by the AI and returns the result.
 *
 * @param sql The SQL query string to execute.
 * @param db The DuckDB database instance.
 * @returns A promise that resolves to the query result data.
 */
export async function executeSQL(
  sql: string,
  db: duckdb.Database
): Promise<any[]> {
  validateSQL(sql)

  return new Promise((resolve, reject) => {
    db.all(sql, (err, result) => {
      if (err) {
        console.error('SQL Execution Error:', err)
        return reject(err)
      }
      const processedResult = postProcessResult(result)
      resolve(processedResult)
    })
  })
}
